apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "brigade.observer.fullname" . }}
  labels:
    {{- include "brigade.labels" . | nindent 4 }}
    {{- include "brigade.observer.labels" . | nindent 4 }}
