{{- if .Values.artemis.ha.enabled }}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brigade.artemis.fullname" . }}-secondary
  labels:
    {{- include "brigade.labels" . | nindent 4 }}
    {{- include "brigade.artemis.secondary.labels" . | nindent 4 }}
data:

  secondary-config-template.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">

        <ha-policy>
          <replication>
            <slave>
              <group-name>to-be-set-by-configure-secondary-node.sh</group-name>
              <allow-failback>true</allow-failback>
            </slave>
          </replication>
        </ha-policy>

      </core>
    </configuration>

  configure-secondary-node.sh: |-
    set -e
    echo Copying common configuration
    cp /opt/common-config/common-config-template.xml /var/lib/artemis/etc-override/broker-10.xml

    echo Assigning node as secondary
    cp /opt/secondary-config/secondary-config-template.xml /var/lib/artemis/etc-override/broker-20.xml 

    GROUPNAME=$(echo ${HOSTNAME} | sed -re 's/(-primary|-secondary)//')
    echo Setting the group-name for secondary to ${GROUPNAME}
    xmlstarlet ed -L \
    -N activemq="urn:activemq" \
    -N core="urn:activemq:core" \
    -u "/activemq:configuration/core:core/core:ha-policy/core:replication/core:slave/core:group-name" \
    -v "${GROUPNAME}" /var/lib/artemis/etc-override/broker-20.xml

    echo Setting the connector-ref to ${HOSTNAME}
    xmlstarlet ed -L \
    -N activemq="urn:activemq" \
    -N core="urn:activemq:core" \
    -u "/activemq:configuration/core:core/core:cluster-connections/core:cluster-connection[@name='{{ include "brigade.artemis.fullname" $root }}']/core:connector-ref" \
    -v "${HOSTNAME}" /var/lib/artemis/etc-override/broker-10.xml
{{- end }}
