apiVersion: v2
name: brigade
description: |
  A Helm chart for Brigade
type: application
version: 0.1.0
appVersion: v0.1.0
sources:
- https://github.com/brigadecore/brigade
maintainers:
- name: The Brigade Maintainers
  email: cncf-brigade-maintainers@lists.cncf.io
dependencies:
- name: mongodb
  version: 10.3.7
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
