apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brigade-prometheus.nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brigade-prometheus.labels" . | nindent 4 }}
    {{- include "brigade-prometheus.nginx.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    events {
        worker_connections  4096;  ## Default: 1024
    }

    http {
        server {
            listen 80;
            root /usr/share/nginx/html;
            index index.html index.htm;

            location / {
              proxy_pass            http://localhost:3000/;
              proxy_set_header      Authorization "";
              auth_basic            "Administrator’s Area";
              auth_basic_user_file  /etc/nginx/.htpasswd; 
            }
        }
    }
  
  .htpasswd: |-
    {{ htpasswd .Values.grafana.auth.username .Values.grafana.auth.password }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brigade-prometheus.grafana.fullname" . }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brigade-prometheus.labels" . | nindent 4 }}
    {{- include "brigade-prometheus.grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |-
    apiVersion: 1

    datasources:
    - name: Brigade-metrics
      type: prometheus
      access: proxy
      isDefault: true
      url: http://{{ include "brigade-prometheus.prometheus.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
