apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-{{ include "brigade-prometheus.grafana.fullname" . }}
  labels:
    {{- include "brigade-prometheus.labels" . | nindent 4 }}
    {{- include "brigade-prometheus.grafana.labels" . | nindent 4 }}
spec:  
  storageClassName: manual  
  accessModes:
   - ReadWriteMany
  resources:
   requests:   
     storage: 1Gi