apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brigade-prometheus.grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brigade-prometheus.labels" . | nindent 4 }}
    {{- include "brigade-prometheus.grafana.labels" . | nindent 4 }}
stringData:
  adminUsername: {{ .Values.grafana.auth.username }}
  adminPassword: {{ .Values.grafana.auth.password }}
