apiVersion: v1
kind: Service
metadata:
  name: {{ include "brigade-prometheus.grafana.fullname" . }}
  labels:
    {{- include "brigade-prometheus.labels" . | nindent 4 }}
    {{- include "brigade-prometheus.grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    {{- if .Values.grafana.auth.proxy }}
  - port: 80
    targetPort: 80
    {{- else }}
  - port: 3000
    targetPort: 3000
    {{- end }}
    {{- if and (or (eq .Values.grafana.service.type "NodePort") (eq .Values.grafana.service.type "LoadBalancer")) .Values.grafana.service.nodePort}}
    nodePort: {{ .Values.grafana.service.nodePort }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "brigade-prometheus.selectorLabels" . | nindent 8 }}
    {{- include "brigade-prometheus.grafana.labels" . | nindent 8 }}
