{
 "title": "Brigade",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Running Workers Duration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "brigade_all_running_workers_duration",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Events by Worker Phase",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_all_workers_by_phase", "legendFormat": "{{ workerPhase }}" }
   ]
  },
  {
   "title": "Total Brigade Projects",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_projects_total" }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_users_total" }
   ]
  },
  {
   "title": "Running Worker Duration History",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "brigade_all_running_workers_duration",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Total Service Accounts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_service_accounts_total" }
   ]
  },
  {
   "title": "Current Running Jobs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_running_jobs_total" }
   ]
  },
  {
   "title": "Running Job History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 21 },
   "targets": [
    { "expr": "brigade_running_jobs_total" }
   ]
  },
  {
   "title": "Current Pending Jobs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_pending_jobs_total" }
   ]
  },
  {
   "title": "Pending Job History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 30 },
   "targets": [
    { "expr": "brigade_pending_jobs_total" }
   ]
  },
  {
   "title": "Current Pending Workers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "brigade_all_workers_by_phase{workerPhase=\"PENDING\"}"
    }
   ]
  },
  {
   "title": "Pending Workers History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 39 },
   "targets": [
    {
     "expr": "brigade_all_workers_by_phase{workerPhase=\"PENDING\"}"
    }
   ]
  }
 ]
}