apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brigade.artemis.fullname" . }}
  labels:
    {{- include "brigade.labels" . | nindent 4 }}
    {{- include "brigade.artemis.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.artemis.password }}
  password:  {{ quote .Values.artemis.password }}
  {{- else }}
  password: {{ randAlphaNum 20 }}
  {{- end }}
