{
 "title": "Brigade",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running Jobs Durations",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "brigade_all_running_jobs_duration",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "All Running Workers Duration",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "brigade_all_running_workers_duration",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_users_total" }
   ]
  },
  {
   "title": "All Jobs by Phase",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_all_jobs_by_phase", "legendFormat": "{{ jobPhase }}" }
   ]
  },
  {
   "title": "All Workers By Phase",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_all_workers_by_phase", "legendFormat": "{{ workerPhase }}" }
   ]
  },
  {
   "title": "Current Running Jobs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_running_jobs_total" }
   ]
  },
  {
   "title": "Total Running Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 22 },
   "targets": [
    { "expr": "brigade_running_jobs_total" }
   ]
  },
  {
   "title": "Current Pending Workers",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_pending_workers_total" }
   ]
  },
  {
   "title": "Total Pending Workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 31 },
   "targets": [
    { "expr": "brigade_pending_workers_total" }
   ]
  },
  {
   "title": "Current Failed Workers",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_failed_workers_total" }
   ]
  },
  {
   "title": "Total Failed Workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 40 },
   "targets": [
    { "expr": "brigade_failed_workers_total" }
   ]
  }
 ]
}