apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brigade.scheduler.fullname" . }}
  labels:
    {{- include "brigade.labels" . | nindent 4 }}
    {{- include "brigade.scheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ randAlphaNum 30 }}
