apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "brigade.scheduler.fullname" . }}
  labels:
    {{- include "brigade.labels" . | nindent 4 }}
    {{- include "brigade.scheduler.labels" . | nindent 4 }}
