apiVersion: v1
kind: Service
metadata:
  name: {{ include "brigade.apiserver.fullname" . }}
  labels:
    {{- include "brigade.labels" . | nindent 4 }}
    {{- include "brigade.apiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
  {{- if .Values.apiserver.tls.enabled }}
  - port: 443
  {{- else }}
  - port: 80
  {{- end }}
    targetPort: 8080
    {{- if and (or (eq .Values.apiserver.service.type "NodePort") (eq .Values.apiserver.service.type "LoadBalancer")) .Values.apiserver.service.nodePort}}
    nodePort: {{ .Values.apiserver.service.nodePort }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "brigade.selectorLabels" . | nindent 8 }}
    {{- include "brigade.apiserver.labels" . | nindent 8 }}
